/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20PermitInternal,
  IERC20PermitInternalInterface,
} from "../../../../../../@solidstate/contracts/token/ERC20/permit/IERC20PermitInternal";

const _abi = [
  {
    inputs: [],
    name: "ERC20Permit__ExpiredDeadline",
    type: "error",
  },
  {
    inputs: [],
    name: "ERC20Permit__InvalidSignature",
    type: "error",
  },
] as const;

export class IERC20PermitInternal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20PermitInternalInterface {
    return new utils.Interface(_abi) as IERC20PermitInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20PermitInternal {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC20PermitInternal;
  }
}
