/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Permit__factory } from "./IERC20Permit__factory";
export { IERC20PermitInternal__factory } from "./IERC20PermitInternal__factory";
export { IERC2612__factory } from "./IERC2612__factory";
