/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export * as enumerable from "./enumerable";
export * as metadata from "./metadata";
export { ISolidStateERC1155__factory } from "./ISolidStateERC1155__factory";
