/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC1155Metadata__factory } from "./IERC1155Metadata__factory";
export { IERC1155MetadataInternal__factory } from "./IERC1155MetadataInternal__factory";
