/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export * as extended from "./extended";
export * as metadata from "./metadata";
export * as permit from "./permit";
export { ISolidStateERC20__factory } from "./ISolidStateERC20__factory";
