/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "ERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Permit__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECDSA__factory>;
    getContractFactory(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712__factory>;
    getContractFactory(
      name: "Math",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Math__factory>;
    getContractFactory(
      name: "Nonces",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nonces__factory>;
    getContractFactory(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortStrings__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "IOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOwnable__factory>;
    getContractFactory(
      name: "IOwnableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOwnableInternal__factory>;
    getContractFactory(
      name: "ISafeOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISafeOwnable__factory>;
    getContractFactory(
      name: "ISafeOwnableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISafeOwnableInternal__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "OwnableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableInternal__factory>;
    getContractFactory(
      name: "SafeOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeOwnable__factory>;
    getContractFactory(
      name: "SafeOwnableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeOwnableInternal__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Internal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Internal__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "IERC173Internal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173Internal__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC20Internal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Internal__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Internal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Internal__factory>;
    getContractFactory(
      name: "ERC165Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165Base__factory>;
    getContractFactory(
      name: "ERC165BaseInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165BaseInternal__factory>;
    getContractFactory(
      name: "IERC165Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165Base__factory>;
    getContractFactory(
      name: "IERC165BaseInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165BaseInternal__factory>;
    getContractFactory(
      name: "DiamondBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondBase__factory>;
    getContractFactory(
      name: "IDiamondBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondBase__factory>;
    getContractFactory(
      name: "DiamondFallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondFallback__factory>;
    getContractFactory(
      name: "IDiamondFallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondFallback__factory>;
    getContractFactory(
      name: "ISolidStateDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISolidStateDiamond__factory>;
    getContractFactory(
      name: "DiamondReadable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondReadable__factory>;
    getContractFactory(
      name: "IDiamondReadable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondReadable__factory>;
    getContractFactory(
      name: "SolidStateDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SolidStateDiamond__factory>;
    getContractFactory(
      name: "DiamondWritable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondWritable__factory>;
    getContractFactory(
      name: "DiamondWritableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondWritableInternal__factory>;
    getContractFactory(
      name: "IDiamondWritable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondWritable__factory>;
    getContractFactory(
      name: "IDiamondWritableInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondWritableInternal__factory>;
    getContractFactory(
      name: "IProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProxy__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "IReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReentrancyGuard__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "IERC1155Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Base__factory>;
    getContractFactory(
      name: "IERC1155BaseInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155BaseInternal__factory>;
    getContractFactory(
      name: "IERC1155Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Enumerable__factory>;
    getContractFactory(
      name: "ISolidStateERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISolidStateERC1155__factory>;
    getContractFactory(
      name: "IERC1155Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Metadata__factory>;
    getContractFactory(
      name: "IERC1155MetadataInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataInternal__factory>;
    getContractFactory(
      name: "IERC20Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Base__factory>;
    getContractFactory(
      name: "IERC20BaseInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20BaseInternal__factory>;
    getContractFactory(
      name: "IERC20Extended",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Extended__factory>;
    getContractFactory(
      name: "IERC20ExtendedInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20ExtendedInternal__factory>;
    getContractFactory(
      name: "ISolidStateERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISolidStateERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20PermitInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20PermitInternal__factory>;
    getContractFactory(
      name: "IERC2612",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC2612__factory>;
    getContractFactory(
      name: "IERC721Base",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Base__factory>;
    getContractFactory(
      name: "IERC721BaseInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721BaseInternal__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "ISolidStateERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISolidStateERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721MetadataInternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721MetadataInternal__factory>;
    getContractFactory(
      name: "AddressUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AddressUtils__factory>;
    getContractFactory(
      name: "UintUtils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UintUtils__factory>;
    getContractFactory(
      name: "Gmxpad",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Gmxpad__factory>;
    getContractFactory(
      name: "Launchpad",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Launchpad__factory>;
    getContractFactory(
      name: "Setting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Setting__factory>;
    getContractFactory(
      name: "Stake",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Stake__factory>;
    getContractFactory(
      name: "Vesting",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Vesting__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "GMXToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GMXToken__factory>;
    getContractFactory(
      name: "XXToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.XXToken__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC5267",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Burnable>;
    getContractAt(
      name: "ERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Permit>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ECDSA",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ECDSA>;
    getContractAt(
      name: "EIP712",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712>;
    getContractAt(
      name: "Math",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Math>;
    getContractAt(
      name: "Nonces",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Nonces>;
    getContractAt(
      name: "ShortStrings",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortStrings>;
    getContractAt(
      name: "Strings",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "IOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOwnable>;
    getContractAt(
      name: "IOwnableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOwnableInternal>;
    getContractAt(
      name: "ISafeOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISafeOwnable>;
    getContractAt(
      name: "ISafeOwnableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISafeOwnableInternal>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "OwnableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableInternal>;
    getContractAt(
      name: "SafeOwnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeOwnable>;
    getContractAt(
      name: "SafeOwnableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeOwnableInternal>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Internal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Internal>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC173",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173>;
    getContractAt(
      name: "IERC173Internal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173Internal>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC20Internal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Internal>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Internal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Internal>;
    getContractAt(
      name: "ERC165Base",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165Base>;
    getContractAt(
      name: "ERC165BaseInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165BaseInternal>;
    getContractAt(
      name: "IERC165Base",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165Base>;
    getContractAt(
      name: "IERC165BaseInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165BaseInternal>;
    getContractAt(
      name: "DiamondBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondBase>;
    getContractAt(
      name: "IDiamondBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondBase>;
    getContractAt(
      name: "DiamondFallback",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondFallback>;
    getContractAt(
      name: "IDiamondFallback",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondFallback>;
    getContractAt(
      name: "ISolidStateDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISolidStateDiamond>;
    getContractAt(
      name: "DiamondReadable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondReadable>;
    getContractAt(
      name: "IDiamondReadable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondReadable>;
    getContractAt(
      name: "SolidStateDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SolidStateDiamond>;
    getContractAt(
      name: "DiamondWritable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondWritable>;
    getContractAt(
      name: "DiamondWritableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondWritableInternal>;
    getContractAt(
      name: "IDiamondWritable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondWritable>;
    getContractAt(
      name: "IDiamondWritableInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondWritableInternal>;
    getContractAt(
      name: "IProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IProxy>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "IReentrancyGuard",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IReentrancyGuard>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "IERC1155Base",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Base>;
    getContractAt(
      name: "IERC1155BaseInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155BaseInternal>;
    getContractAt(
      name: "IERC1155Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Enumerable>;
    getContractAt(
      name: "ISolidStateERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISolidStateERC1155>;
    getContractAt(
      name: "IERC1155Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Metadata>;
    getContractAt(
      name: "IERC1155MetadataInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataInternal>;
    getContractAt(
      name: "IERC20Base",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Base>;
    getContractAt(
      name: "IERC20BaseInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20BaseInternal>;
    getContractAt(
      name: "IERC20Extended",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Extended>;
    getContractAt(
      name: "IERC20ExtendedInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20ExtendedInternal>;
    getContractAt(
      name: "ISolidStateERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISolidStateERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20PermitInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20PermitInternal>;
    getContractAt(
      name: "IERC2612",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC2612>;
    getContractAt(
      name: "IERC721Base",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Base>;
    getContractAt(
      name: "IERC721BaseInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721BaseInternal>;
    getContractAt(
      name: "IERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Enumerable>;
    getContractAt(
      name: "ISolidStateERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ISolidStateERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721MetadataInternal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721MetadataInternal>;
    getContractAt(
      name: "AddressUtils",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AddressUtils>;
    getContractAt(
      name: "UintUtils",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UintUtils>;
    getContractAt(
      name: "Gmxpad",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Gmxpad>;
    getContractAt(
      name: "Launchpad",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Launchpad>;
    getContractAt(
      name: "Setting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Setting>;
    getContractAt(
      name: "Stake",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Stake>;
    getContractAt(
      name: "Vesting",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Vesting>;
    getContractAt(
      name: "IERC20Permit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "GMXToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GMXToken>;
    getContractAt(
      name: "XXToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.XXToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
