/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Base } from "./IERC1155Base";
export type { IERC1155BaseInternal } from "./IERC1155BaseInternal";
