/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Base__factory } from "./IERC20Base__factory";
export { IERC20BaseInternal__factory } from "./IERC20BaseInternal__factory";
