/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GMXPToken__factory } from "./GMXPToken__factory";
export { XXToken__factory } from "./XXToken__factory";
