/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GMXToken__factory } from "./GMXToken__factory";
export { XXToken__factory } from "./XXToken__factory";
