/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Base } from "./IERC20Base";
export type { IERC20BaseInternal } from "./IERC20BaseInternal";
