/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Permit } from "./IERC20Permit";
export type { IERC20PermitInternal } from "./IERC20PermitInternal";
export type { IERC2612 } from "./IERC2612";
