/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721MetadataInternal } from "./IERC721MetadataInternal";
