/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Metadata } from "./IERC1155Metadata";
export type { IERC1155MetadataInternal } from "./IERC1155MetadataInternal";
