/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as extended from "./extended";
export type { extended };
import type * as metadata from "./metadata";
export type { metadata };
import type * as permit from "./permit";
export type { permit };
export type { ISolidStateERC20 } from "./ISolidStateERC20";
