/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC721Base } from "./IERC721Base";
export type { IERC721BaseInternal } from "./IERC721BaseInternal";
